version: '3.8'

services:
  yolov8:
    image: ultralytics/ultralytics:latest
    container_name: yolov8
    working_dir: /workspace
    volumes:
      - ./dataset:/workspace/dataset         # Dataset local
      - ./runs:/workspace/runs               # Resultados do treino
    stdin_open: true
    tty: true
    command: yolo detect train data=dataset/data.yaml model=yolov8n.pt epochs=100 imgsz=640,360 batch=32
